"""init clean

Revision ID: 6926bd991a8f
Revises: 
Create Date: 2026-03-28 17:10:29.328619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6926bd991a8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_notaria', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('comuna', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('correo_oficial', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('horario_apertura', sa.String(length=20), nullable=False),
    sa.Column('horario_cierre', sa.String(length=20), nullable=False),
    sa.Column('horas_minimas_atencion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tarifa', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('modulo', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=50), nullable=False),
    sa.Column('nombre_reclamante', sa.String(length=150), nullable=False),
    sa.Column('rut_reclamante', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('adjunto_path', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.Column('responded_by', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['responded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=50), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('solicitante_nombre', sa.String(length=150), nullable=True),
    sa.Column('solicitante_rut', sa.String(length=20), nullable=True),
    sa.Column('contenido_resumen', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('original_file_path', sa.String(length=255), nullable=True),
    sa.Column('signed_file_path', sa.String(length=255), nullable=True),
    sa.Column('copy_file_path', sa.String(length=255), nullable=True),
    sa.Column('hash_signed_file', sa.String(length=255), nullable=True),
    sa.Column('provider_signature', sa.String(length=100), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('verification_code', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_signed_by', sa.Integer(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['uploaded_signed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio'),
    sa.UniqueConstraint('verification_code')
    )
    op.create_table('sanction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('resolucion', sa.Text(), nullable=True),
    sa.Column('fecha_sancion', sa.Date(), nullable=False),
    sa.Column('fecha_publicacion_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_publicacion_fin', sa.Date(), nullable=True),
    sa.Column('publica', sa.Boolean(), nullable=True),
    sa.Column('creada_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creada_por'], ['user.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sanction')
    op.drop_table('document')
    op.drop_table('complaint')
    op.drop_table('audit_log')
    op.drop_table('user')
    op.drop_table('service')
    op.drop_table('office_config')
    # ### end Alembic commands ###
