"""agrega flujo firma externa en documentos2

Revision ID: 8961515b3d47
Revises: 6926bd991a8f
Create Date: 2026-03-28 21:07:40.130791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8961515b3d47'
down_revision = '6926bd991a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enviado_firma_externa', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_envio_firma', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('observacion_firma', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('observacion_firma')
        batch_op.drop_column('fecha_envio_firma')
        batch_op.drop_column('enviado_firma_externa')

    # ### end Alembic commands ###
